# site settings
title: Jeremias Menichelli | Web Developer
author: Jeremias Menichelli
description: "My name is up there so you need me to tell you that. In case you don't know it I love spending my days building cool stuff on the web."
url: "http://jeremenichelli.github.io"
baseurl: ""

# build settings
port: 4000
highlighter: pygments
markdown: redcarpet
permalink: /:year/:month/:title
