title: Jeremias Menichelli | Web Developer
author: Jeremias Menichelli
url: https://jeremenichelli.github.io

port: 4000
safe: true
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:title
gems:
  - jekyll-sitemap
