title: Jeremias Menichelli | Web Developer
author: Jeremias Menichelli

port: 4000
auto: true
safe: true
server: true
markdown: redcarpet
pygments: true
permalink: /:year/:month/:title
gems:
  - jekyll-sitemap
