# site settings
title: Jeremias Menichelli | Web Developer
author: Jeremias Menichelli
description: "My name is Jeremias Menichelli and I love the web, that's why I work as a front end developer to make it better, building beautiful and scalable products using JavaScript and CSS, with a big eye on usability and performance."
url: "https://jeremenichelli.github.io"
baseurl: ""

# build settings
port: 4000
exclude: [ 'node_modules' ]
markdown: kramdown
kramdown:
  input: GFM
permalink: /:year/:month/:title
